### ISSUE TITLE
[BUG]: Latitude and Longitude of static IPs sometimes doesn't match ZScaler internal value.

### ISSUE THREAD

**Issue by chris-bornmann** [mitchos/pyZscaler#136]
Describe the bug
----------------------
When I use the zia.traffic.list_static_ips() API to fetch all the static IP addresses **some** of the records have latitude and longitude values that are _slightly_ off from what the GUI shows.  That's not a big concern, except that I'm using the API to generate Terraform, and it also causes mismatches when it's time for a "terraform apply".

I believe in all cases the "Selection" value ("geo_override" in Terraform) is set to "Automatic" (or "false" in Terraform), which may be where the confusion comes from, but there are many static IP resources with "Automatic" set where the latitude and longitude match.

The latitude and longitude shown there are:
```
latitude        =  33.1891
longitude       =  -117.3864
```

The API returns:
```
latitude        =  33.2077
longitude       =  -117.348
```

They are close but not exact.  I checked one and it was about 7 miles off.  I am using the API to generate an initial batch of Terraform though, and the mismatch causes changes to be applied.  If there's a way to avoid it that would be nice.

**To Reproduce**
1. Create a static IP resource with the "Selection" set to "Automatic".
1. Use the zia.traffic.list_static_ips API to dump traffic_forwarding_static_ips.
1. Sometimes the latitude and longitude won't match.

Expected behavior
------------------------
The latitude and longitude should match what is in the ZIA ZScaler resource.

Screenshots
----------------
<img width="751" alt="Screen Shot 2022-08-29 at 10 15 00 AM" src="https://user-images.githubusercontent.com/5652438/187258876-7002540e-ddc8-4b45-82fd-e8575c5721b3.png">

Additional context
-------------------------
pyzscaler 1.3.0.
Python 3.10.4.

**Comment by mitchos** [comment]
Hey Chris thanks for the detailed information, I'll check this out today and see if there's any predictable way this is occurring. If not then it might be something we need to raise with Zscaler. Will let you know how my testing pans out. 

(Sorry for the long time for response I've been having a bit of a break)

**Comment by mitchos** [comment]
@chris-bornmann I'm just coming back to this one as I feel like it might be resolved by now given some recent updates to ZIA.

I've added 5 different random static IPs and the geo location data is matching between the UI and API - do you mind just retesting on your end to see if this is still occurring?

**Comment by mitchos** [comment]
Closing as this doesn't appear to be an issue anymore
