### ISSUE TITLE
[BUG]: update_segment and tcp_ports and udp_ports

### ISSUE THREAD

**Issue by charlieyi2000** [mitchos/pyZscaler#153]
No matter what I enter for tcp_ports or udp_ports with update_segment nothing is updated.

**Comment by mitchos** [comment]
Hi @charlieyi2000 

I've been able to replicate this - it's indeed a bug. Will start on a fix for this.

**Comment by mitchos** [comment]
Fix has been pushed to the develop branch, this will be included in the next release which shouldn't be too far off. 

Thanks for raising this to our attention @charlieyi2000

**Comment by charlieyi2000** [comment]
Thank you for the prompt response and great work.
