### ISSUE TITLE
Sandbox File Submittal Not Functioning 

### ISSUE THREAD

**Issue by schotsal** [mitchos/pyZscaler#160]
Describe the bug
----------------------
'sandbox.submit_file' function does not have the ability to select the sandbox endpoint to submit the file to and is rendered non-functional.

**To Reproduce**
1. use the function zia.sandbox.submit_file('malware.exe', force=True) in a program
2. the file will always be submitted to "https://csbapi.zscaler.net/zscsb/submit"
3. the endpoint selection needs to match the users zscaler subscription for the function to be useful

Expected behavior
------------------------
Need to be able to multi-select sandbox endpoints - something similar to what vips.py does except for sandbox endpoints..  this could also be a simple dictionary lookup as the determination is simpler than ZENs.

**Comment by mitchos** [comment]
Taking a look at this in conjunction with #162
