### ISSUE TITLE
[FEAT] add DLP engine get and post

### ISSUE THREAD

**Issue by MrP1xel** [mitchos/pyZscaler#226]
Hello,
can you please add the support for GET and POST for the DLP engine ?

API : https://help.zscaler.com/zia/data-loss-prevention#/dlpEngines-get

**Comment by mitchos** [comment]
Hi @MrP1xel I'll add this into the next release (1.6.0) which should be some time this week. Thanks for raising!

**Comment by MrP1xel** [comment]
Hello Mitchos ! Thanks a lot for that !

**Comment by MrP1xel** [comment]
Hello, can't see this feature into the last release notes or in the code, maybe for the next release :)
