### ISSUE TITLE
[BUG]: delete_urls_from_category doesn't accept list variable type

### ISSUE THREAD

**Issue by sisaac-vmd** [mitchos/pyZscaler#259]
When working with the ZIA module and URL categories, passing a list variable, let's call it 'urls', to zia.url_categories.add_urls_to_category(url_category_id, urls=urls) works just fine but passing the same exact variable to zia.url_categories.delete_urls_from_category(url_category_id, urls=urls) results in an error. 

Error message - "INVALID_INPUT_ARGUMENT","message":"At least 1 URL or keyword should be entered"

Here's the code if it helps:
-----------------------------------------------------------------------------------------------------------------

from pyzscaler import ZIA
api_key = "xxxxxxxxxxxxxxxxxxxx"
cloud = "xxxxxxxxxxxxxxxx"
username = "xxxxxxxxxxxxxxxxxx"
password = "xxxxxxxxxxxxxxxxxxxx"
input_file = "xxxxxxxxxxxxxxxxxxx.txt"
url_category_id = "xxxxxxxxxxxxxxx"
zia = ZIA(api_key=api_key, cloud=cloud, username=username, password=password)
file_object = open(input_file,"r")
contents = file_object.read()
contents_format = contents.rstrip()
urls = contents_format.split("\n")
file_object.close()
s = zia.url_categories.delete_urls_from_category(url_category_id, urls=urls)
zia.config.activate()
zia.session.delete()
---------------------------------------------------------------------------------------------------------------

If I swap "delete_urls_from_category" with "add_urls_to_category", no issues.

**Comment by mitchos** [comment]
Taking a look at this

**Comment by mitchos** [comment]
Hi @sisaac-vmd you're hitting one of Zscaler's deliciously ambiguous error messages. ZIA will **not** let you remove all URLs from a category via API. This error message should be a bit more explicit and say that the category must retain at least 1 or more URL. You can see that I'm able to use your script correctly below if I leave 1 URL in the category, in this case:

1. I've started with `test.com` being the sole URL. 
2. I then add 3 URLs
3. I delete the 3 URLs
4. I then try to delete the last URL in the category, triggering the same error message

## Code

```python
file_object = open("test_url.txt", "r")
contents = file_object.read()
contents_format = contents.rstrip()
urls = contents_format.split("\n")
file_object.close()
category = "CUSTOM_02"
print(urls)
print(type(urls))
with ZIA() as zia:
    print(zia.url_categories.add_urls_to_category(category, urls))
    print(zia.url_categories.delete_urls_from_category(category, urls))
    print(zia.url_categories.delete_urls_from_category(category, ["test.com"]))
```

## Output
Here is the output produced

### Contents of test_url.txt
`['example.com', 'example2.com', 'example3.com']`

### Type for urls variable
`<class 'list'>`

### Return from zia.url_categories.add_urls_to_category()

We can see the URLs are successfully added to the CUSTOM_02 category

```json
{
   "id":"CUSTOM_02",
   "configured_name":"new_ui_cat",
   "keywords":[
      
   ],
   "keywords_retaining_parent_category":[
      
   ],
   "urls":[
      "test.com",
      "example3.com",
      "example.com",
      "example2.com"
   ],
   "db_categorized_urls":[
      
   ],
   "custom_category":true,
   "editable":true,
   "description":"CUSTOM_02_DESC",
   "type":"URL_CATEGORY",
   "val":129,
   "custom_urls_count":4,
   "urls_retaining_parent_category_count":0,
   "custom_ip_ranges_count":0,
   "ip_ranges_retaining_parent_category_count":0
}
```

### Return from zia.url_categories.delete_urls_from_category()

We can see the URLs are successfully removed, leaving the test.com URL that existed prior to running this code

```json
{
   "id":"CUSTOM_02",
   "configured_name":"new_ui_cat",
   "keywords":[
      
   ],
   "keywords_retaining_parent_category":[
      
   ],
   "urls":[
      "test.com"
   ],
   "db_categorized_urls":[
      
   ],
   "custom_category":true,
   "editable":true,
   "description":"CUSTOM_02_DESC",
   "type":"URL_CATEGORY",
   "val":129,
   "custom_urls_count":1,
   "urls_retaining_parent_category_count":0,
   "custom_ip_ranges_count":0,
   "ip_ranges_retaining_parent_category_count":0
}
```

## Trying to delete the last url (test.com)
```[400: PUT] https://zsapi.zscaler.net/api/v1/urlCategories/CUSTOM_02?action=REMOVE_FROM_LIST body=b'{"code":"INVALID_INPUT_ARGUMENT","message":"At least 1 URL or keyword should be entered"}'```


## Suggestions for improvement
pyZscaler has a built-in context-manager that will handle deauthentication automatically. This will simplify your code and ensure that there are never any configuration changes hanging and awaiting activation. When your API user session is logged out, all changes queued up will be automatically activated.

Further, you can use a context-manager for your file operations to ensure again that you don't have any files left hanging open. 

See below for how I would refactor the code provided:

```python
# Use the context manager for handling the ZIA session
with ZIA(api_key=api_key, cloud=cloud, username=username, password=password) as zia:
    # Using a context manager for file operations
    try:
        with open(input_file, "r") as file_object:
            contents = file_object.read().rstrip()
            urls = contents.split("\n")
            
        # Perform the URL removal operation
        response = zia.url_categories.delete_urls_from_category(url_category_id, urls=urls)
        print(f"Response: {response}")

    # Handle exceptions here or raise as e
    except Exception as e:
        print(f"An error occurred: {e}")

# By the time execution hits here, the file will be closed and ZIA will have activated the changes
```

**Comment by sisaac-vmd** [comment]
@mitchos Thank you! What an excellent write-up! I've updated my approach accordingly. Please feel free to close the issue.
