### ISSUE TITLE
"Real data" in a docstring?

### ISSUE THREAD

**Issue by daxm** [mitchos/pyZscaler#50]
Not sure if this is actually an issue but it appears there might be real data in an example in the docstring for create_token in AuthenticatedSessionAPI in ZPA's session.py file.

**Comment by daxm** [comment]
Before I go messing with altering it (if it is real) I figure I better see whether the PR is worth the effort.

**Comment by mitchos** [comment]
Are we talking about this bit?

``` python
 Examples:
            >>> zia.session.create(api_key='12khsdfh3289',
            ...    username='admin@example.com',
            ...    password='MyInsecurePassword')
```

The API key there is definitely fake, I just mashed the keyboard and truncated it to 12 chars 😄😈 

Might as well raise here that all of the IDs were either taken from the examples in the ZIA documentation or randomly generated (these ones normally start with a 9 if I recall).
