### ISSUE TITLE
[BUG]: ZPA : SCIM Groups - 404 - No handler found

### ISSUE THREAD

**Issue by LetMeR00t** [mitchos/pyZscaler#85]
Describe the bug
----------------------
It seems that one call of the API is returning a 404 error from Zscaler with "No handler found"

**To Reproduce**
Just perform a zpa.scim_groups.list_groups() to have the error.
The URL used by the API ("https://config.private.zscaler.com/userconfig/v1/customers/.../scimgroup?page=1") seems not appearing anymore on the ZPA API reference : https://help.zscaler.com/zpa/api-reference

Expected behavior
------------------------
We would expect to have the list of groups

Screenshots
----------------
![image](https://user-images.githubusercontent.com/10530375/155402940-d9a8863f-bbe6-4954-92e1-4600c7d7062d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari]: Not a browser, it's using the requests library of Python
 - Version [e.g. 22]: 2.27.1

Additional context
-------------------------
-

**Comment by mitchos** [comment]
Thanks for logging this issue @LetMeR00t. Fix is on the way.

Keep an eye out for a new release in the next couple of hours.
