### ISSUE TITLE
Add Support for ZPA SCIM Operations Endpoints

### ISSUE THREAD

**Issue by mitchos** [mitchos/pyZscaler#98]
## Overview
ZPA's SCIM API has been made public and there are a number of API endpoints available now to allow CRUD operations on SCIM entities.

pyZscaler should support these endpoints to allow users to perform CRUD operations on SCIM entities.

## Reference

- https://help.zscaler.com/zpa/scim-api-examples#Curl

**Comment by cyberears** [comment]
would really like this as well , thanks for your amazing work
